# Mod Settings
mod.name = Player Handling Customizer
mod.id = player_handling_customizer
mod.author = G'lek Tarssza
mod.description = A Minecraft mod that customizes how player targeting and damaging is handled.
mod.version = 0.1.0
mod.homepage = https://codefloe.com/glektarssza/minecraft-player-handling-customizer
mod.credits = The GTNH Team for RetroFuturaGradle, G'lek Tarssza for the mod itself.
mod.base_group = com.glektarssza
mod.archive_base_name = player-handling-customizer-forge
mod.dependencies =
mod.version.accepted_save_range = [0.1.0,0.2.0)
mod.version.accepted_remote_range = [0.1.0,0.2.0)
mod.sided_proxy.client_side = com.glektarssza.player_handling_customizer.ClientProxy
mod.sided_proxy.server_side = com.glektarssza.player_handling_customizer.ServerProxy
mod.gui_factory =
mod.update_manifest_url = https://codefloe.com/glektarssza/minecraft-player-handling-customizer/raw/branch/main/forgeUpdateManifest.json
mod.signature =
mod.mixins.enabled = true
mod.mixins.hot_swap.enabled = true

# Minecraft Settings
minecraft.version = 1.12.2
minecraft.version.range = [1.12.2,1.13.0)

# Java Settings
java.compiler.file.encoding = UTF-8

# Gradle Settings
org.gradle.caching = true
org.gradle.configuration-cache = true
